port: 7890

socks-port: 7891

ipv6: false

external-controller: 127.0.0.1:9090

external-ui: dashboard

hosts:
  'localhost': 127.0.0.1

dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
  enhanced-mode: fake-ip
  fake-ip-filter:
    - '*.lan'
  nameserver:
    - dhcp://以太网

tun:
  enable: true
  stack: system
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true

proxies:
  - name: SS
    type: ss
    server: ss.server.domain
    port: 8388
    cipher: aes-256-gcm
    password: password
    udp: true

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - SS

rules:
  - PROCESS-NAME,qbittorrent.exe,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
