port: 7890

socks-port: 7891

ipv6: false

external-controller: 127.0.0.1:9090

external-ui: dashboard

hosts:
  'localhost': 127.0.0.1

dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 223.6.6.6
  enhanced-mode: fake-ip
  fake-ip-filter:
    - '*.lan'
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query

tun:
  enable: true
  stack: system
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true

proxies:
  - name: TROJAN
    type: trojan
    server: trojan.server.domain
    port: 443
    password: password
    udp: true

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - TROJAN

script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443

rules:
  - PROCESS-NAME,qbittorrent.exe,DIRECT
  - SCRIPT,quic,REJECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
