port: 7890

socks-port: 7891

ipv6: false

external-controller: 127.0.0.1:9090

external-ui: dashboard

hosts:
  'localhost': 127.0.0.1

dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
  enhanced-mode: fake-ip
  fake-ip-filter:
    - '*.lan'
  nameserver:
    - https://doh.pub/dns-query

tun:
  enable: true
  stack: system
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true

proxies:
  - name: SS
    type: ss
    server: ss.server.domain
    port: 8388
    cipher: aes-256-gcm
    password: password
    udp: true

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - SS

rules:
  - PROCESS-NAME,qbittorrent.exe,DIRECT
  - IP-CIDR,0.0.0.0/8,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,169.254.0.0/16,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.0.0.0/24,DIRECT
  - IP-CIDR,192.0.2.0/24,DIRECT
  - IP-CIDR,192.88.99.0/24,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,198.18.0.0/15,DIRECT
  - IP-CIDR,198.51.100.0/24,DIRECT
  - IP-CIDR,203.0.113.0/24,DIRECT
  - IP-CIDR,223.255.255.0/24,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,240.0.0.0/4,DIRECT
  - IP-CIDR,255.255.255.255/32,DIRECT
  - IP-CIDR6,::/128,DIRECT
  - IP-CIDR6,::1/128,DIRECT
  - IP-CIDR6,100::/64,DIRECT
  - IP-CIDR6,64:ff9b::/96,DIRECT
  - IP-CIDR6,2001::/32,DIRECT
  - IP-CIDR6,2001:10::/28,DIRECT
  - IP-CIDR6,2001:20::/28,DIRECT
  - IP-CIDR6,2001:db8::/32,DIRECT
  - IP-CIDR6,2002::/16,DIRECT
  - IP-CIDR6,fc00::/7,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT
  - IP-CIDR6,ff00::/8,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
